# Generated by Django 4.1.1 on 2022-10-21 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='image',
            new_name='sub_image',
        ),
        migrations.AlterField(
            model_name='ordermaster',
            name='order_status',
            field=models.CharField(choices=[('cancel', 'cancel'), ('Order booked', 'Order booked'), ('Prepare for dishpatch', 'Prepare for dishpatch'), ('delivered', 'delivered'), ('On the way', 'On the way')], default='Order booked', max_length=50),
        ),
        migrations.AlterField(
            model_name='ordermaster',
            name='payment_status',
            field=models.CharField(choices=[('Failed', 'Failed'), ('Credit', 'Credit'), ('Pending', 'Pending')], default='Pending', max_length=50),
        ),
    ]
