# Generated by Django 4.1.1 on 2022-10-21 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_rename_image_subcategory_sub_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.subcategory'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='status_at',
            field=models.CharField(choices=[('Enable', 'Enable'), ('Desable', 'Desable')], default='Enable', max_length=10),
        ),
        migrations.AlterField(
            model_name='ordermaster',
            name='order_status',
            field=models.CharField(choices=[('cancel', 'cancel'), ('delivered', 'delivered'), ('On the way', 'On the way'), ('Order booked', 'Order booked'), ('Prepare for dishpatch', 'Prepare for dishpatch')], default='Order booked', max_length=50),
        ),
        migrations.AlterField(
            model_name='ordermaster',
            name='payment_status',
            field=models.CharField(choices=[('Failed', 'Failed'), ('Pending', 'Pending'), ('Credit', 'Credit')], default='Pending', max_length=50),
        ),
    ]
