# Generated by Django 4.1.1 on 2022-10-24 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_customerprofile_first_name_customerprofile_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='full_name',
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='status_at',
            field=models.CharField(choices=[('Desable', 'Desable'), ('Enable', 'Enable')], default='Enable', max_length=10),
        ),
        migrations.AlterField(
            model_name='ordermaster',
            name='order_status',
            field=models.CharField(choices=[('Prepare for dishpatch', 'Prepare for dishpatch'), ('On the way', 'On the way'), ('delivered', 'delivered'), ('Order booked', 'Order booked'), ('cancel', 'cancel')], default='Order booked', max_length=50),
        ),
        migrations.AlterField(
            model_name='ordermaster',
            name='payment_status',
            field=models.CharField(choices=[('Credit', 'Credit'), ('Pending', 'Pending'), ('Failed', 'Failed')], default='Pending', max_length=50),
        ),
    ]
