# Generated by Django 4.1.1 on 2022-11-15 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_alter_ordermaster_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='status_at',
            field=models.CharField(choices=[('Enable', 'Enable'), ('Desable', 'Desable')], default='Enable', max_length=10),
        ),
        migrations.AlterField(
            model_name='ordermaster',
            name='order_status',
            field=models.CharField(choices=[('Prepare for dishpatch', 'Prepare for dishpatch'), ('delivered', 'delivered'), ('Order booked', 'Order booked'), ('On the way', 'On the way'), ('cancel', 'cancel')], default='Order booked', max_length=50),
        ),
        migrations.AlterField(
            model_name='ordermaster',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Credit', 'Credit'), ('Failed', 'Failed')], default='Pending', max_length=50),
        ),
    ]
