# Generated by Django 4.1.1 on 2022-11-15 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_alter_customerprofile_status_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermaster',
            name='order_status',
            field=models.CharField(choices=[('Order booked', 'Order booked'), ('Prepare for dishpatch', 'Prepare for dishpatch'), ('On the way', 'On the way'), ('cancel', 'cancel'), ('delivered', 'delivered')], default='Order booked', max_length=50),
        ),
        migrations.AlterField(
            model_name='ordermaster',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Failed', 'Failed'), ('Credit', 'Credit')], default='Pending', max_length=50),
        ),
    ]
